// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlPZ215Xe2XeDVOCw8Lr2BbQXnC41e9xA',
    appId: '1:44808051687:web:58b0180c6f431691977b42',
    messagingSenderId: '44808051687',
    projectId: 'sellr-708b3',
    authDomain: 'sellr-708b3.firebaseapp.com',
    storageBucket: 'sellr-708b3.appspot.com',
    measurementId: 'G-SYX9JCNMCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrkzLzMwwe3t27ymKAZacBndnW8_93FMQ',
    appId: '1:44808051687:android:9574d352926f9c6d977b42',
    messagingSenderId: '44808051687',
    projectId: 'sellr-708b3',
    storageBucket: 'sellr-708b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSSdLhqY61ljCmK07N1mTj9yeR3r6GX78',
    appId: '1:44808051687:ios:89a3a0b3760fbf94977b42',
    messagingSenderId: '44808051687',
    projectId: 'sellr-708b3',
    storageBucket: 'sellr-708b3.appspot.com',
    iosBundleId: 'com.example.sellrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSSdLhqY61ljCmK07N1mTj9yeR3r6GX78',
    appId: '1:44808051687:ios:6f71f53b088723df977b42',
    messagingSenderId: '44808051687',
    projectId: 'sellr-708b3',
    storageBucket: 'sellr-708b3.appspot.com',
    iosBundleId: 'com.example.sellrApp.RunnerTests',
  );
}
